"""
Few-shot examples for SAR narrative generation.
Each example has suspicious activity input (condensed) and the corresponding narrative.
Used by the agent to learn the expected style and to avoid hallucination.
"""

from typing import Any

# Few-shot examples: list of {"input_snippet": {...}, "narrative": "..."}
# Input snippets are simplified for prompt size; full inputs would be used in production.
FEW_SHOT_EXAMPLES: list[dict[str, Any]] = [
    {
        "input_snippet": {
            "case_id": "CASE-2023-001",
            "amount": 95000,
            "date_from": "01/15/2024",
            "date_to": "02/29/2024",
            "subject": {
                "name": "John Doe",
                "type": "Individual",
                "risk_rating": "High",
            },
            "alert": {
                "alert_id": "ALRT-12345",
                "model_name": "Structuring Detection Model",
                "red_flags": ["Structuring"],
            },
            "categories": {
                "Structuring": ["Multiple transactions below CTR threshold"],
                "Fraud": ["Wire"],
                "MoneyLaundering": ["Suspicious EFT/wire transfers"],
            },
            "activities": [
                {
                    "transactions": [
                        {
                            "timestamp": "01/20/2024 10:15:00",
                            "amount_usd": 9500.0,
                            "product_type": "Residential mortgage",
                            "instrument_type": "Funds transfer",
                        },
                        {
                            "timestamp": "01/22/2024 14:30:00",
                            "amount_usd": 8750.0,
                            "product_type": "Home equity loan",
                            "instrument_type": "Funds transfer",
                        },
                    ]
                }
            ],
        },
        "narrative": (
            """
This Suspicious Activity Report (SAR) is filed to report suspected structuring and money laundering activities involving John Doe, an individual with a High risk rating. The activity was identified through Alert ALRT-12345 generated by the Structuring Detection Model and involves multiple wire transfers below the Currency Transaction Report (CTR) threshold.

Between January 15, 2024, and February 29, 2024, the subject John Doe engaged in a pattern of suspicious transactions totaling approximately $95,000. The activity involved multiple wire transfers, each below the $10,000 CTR reporting threshold, suggesting an attempt to avoid regulatory reporting requirements.
On January 20, 2024, at 10:15 AM, a wire transfer of $9,500 was initiated involving a residential mortgage product via funds transfer. This was followed by another wire transfer on January 22, 2024, at 2:30 PM, in the amount of $8,750 involving a home equity loan product via funds transfer.
The pattern of transactions below the reporting threshold, combined with the use of wire transfers and multiple product types, is consistent with structuring behavior designed to evade Bank Secrecy Act reporting requirements. The transactions also exhibit characteristics of money laundering, specifically suspicious EFT/wire transfers.

Based on the pattern of structured transactions below the CTR threshold and the suspicious nature of the wire transfers, this activity warrants filing a SAR. The transactions suggest an attempt to avoid regulatory reporting and may be indicative of money laundering or other illicit financial activity."""
        ),
    },
    {
        "input_snippet": {
            "case_id": "CASE-2023-002",
            "amount": 48750,
            "date_from": "03/01/2024",
            "date_to": "03/18/2024",
            "subject": {
                "name": "Maria Thompson",
                "type": "Individual",
                "risk_rating": "Medium",
            },
            "alert": {
                "alert_id": "ALRT-67890",
                "model_name": "Account Takeover Detection Model",
                "red_flags": ["Account Takeover", "Unauthorized Wire Activity"],
            },
            "categories": {
                "Fraud": ["Account takeover", "Unauthorized password reset"],
                "Cybercrime": ["IP address anomaly", "Multiple failed login attempts"],
                "MoneyLaundering": ["Rapid outgoing wire transfers"],
            },
            "activities": [
                {
                    "transactions": [
                        {
                            "timestamp": "03/05/2024 09:12:00",
                            "amount_usd": 22500.0,
                            "product_type": "Checking account",
                            "instrument_type": "Domestic wire transfer",
                        },
                        {
                            "timestamp": "03/06/2024 11:45:00",
                            "amount_usd": 26250.0,
                            "product_type": "Checking account",
                            "instrument_type": "International wire transfer",
                        },
                    ]
                }
            ],
        },
        "narrative": (
            """
A review of recent account activity associated with Maria Thompson identified indicators consistent with potential account takeover and fraudulent wire transfers. The activity was flagged under Alert ALRT-67890 by the Account Takeover Detection Model following unusual login behavior and subsequent high-value outgoing transactions.

During the period of March 1, 2024 through March 18, 2024, the subject’s checking account experienced multiple failed login attempts originating from previously unseen IP addresses. Shortly thereafter, the account password was reset and significant wire transfers were initiated.

On March 5, 2024 at 9:12 AM, a domestic wire transfer in the amount of $22,500 was processed from the checking account. The following day, on March 6, 2024 at 11:45 AM, an international wire transfer totaling $26,250 was sent to a beneficiary not previously associated with the account. The combined outgoing activity totaled approximately $48,750.

This sequence of events — unauthorized access attempts, credential modification, and rapid transfer of funds to new beneficiaries — deviates from the subject’s established transaction history. The presence of cyber-related indicators and accelerated movement of funds suggests potential unauthorized access and fraudulent activity.

Given the anomalous login patterns and immediate transfer of funds, this matter is considered suspicious and is being reported for further regulatory review."""
        ),
    },
    {
        "input_snippet": {
            "case_id": "CASE-2023-003",
            "amount": 312000,
            "date_from": "04/01/2024",
            "date_to": "05/10/2024",
            "subject": {
                "name": "Global Imports LLC",
                "type": "Business",
                "risk_rating": "High",
            },
            "alert": {
                "alert_id": "ALRT-24680",
                "model_name": "Unusual Business Activity Model",
                "red_flags": [
                    "Trade-Based Money Laundering",
                    "Unusual International Wires",
                ],
            },
            "categories": {
                "MoneyLaundering": ["Trade-based money laundering"],
                "Sanctions": ["High-risk jurisdiction payments"],
                "Fraud": ["Invoice discrepancies"],
            },
            "activities": [
                {
                    "transactions": [
                        {
                            "timestamp": "04/12/2024 13:05:00",
                            "amount_usd": 156000.0,
                            "product_type": "Business operating account",
                            "instrument_type": "International wire transfer",
                        },
                        {
                            "timestamp": "04/25/2024 16:40:00",
                            "amount_usd": 156000.0,
                            "product_type": "Business operating account",
                            "instrument_type": "International wire transfer",
                        },
                    ]
                }
            ],
        },
        "narrative": (
            """
Unusual international payment activity conducted by Global Imports LLC prompted further investigation into potential trade-based money laundering concerns. The activity was identified through Alert ALRT-24680 generated by the Unusual Business Activity Model due to large outbound wires to foreign entities in high-risk jurisdictions.

Between April 1, 2024 and May 10, 2024, the business operating account initiated two international wire transfers totaling approximately $312,000. On April 12, 2024 at 1:05 PM, a transfer of $156,000 was sent to an overseas beneficiary located in a jurisdiction designated as high risk. A second transfer in the same amount was executed on April 25, 2024 at 4:40 PM to a related foreign counterparty.

Documentation provided in support of the transfers reflected inconsistencies between invoice values and the amounts remitted. Additionally, the transaction values materially exceeded the customer’s historical wire activity, and the foreign beneficiaries were recently added without documented prior business engagement.

The combination of high-value international transfers, discrepancies in supporting documentation, and involvement of elevated-risk jurisdictions aligns with common trade-based money laundering typologies. Based on the nature and pattern of the activity, this report is submitted for regulatory review of suspected money laundering conduct."""
        ),
    },
]


def get_few_shot_text() -> str:
    """Format few-shot examples as text for the agent prompt."""
    lines = []
    for i, ex in enumerate(FEW_SHOT_EXAMPLES, 1):
        lines.append(f"--- Example {i} ---")
        lines.append("Input (suspicious activity information):")
        lines.append(str(ex["input_snippet"]))
        lines.append("Generated narrative:")
        lines.append(ex["narrative"])
        lines.append("")
    return "\n".join(lines)
